apiVersion: v1
kind: Service
metadata:
  name: miniedgeapp-eastus-service
spec:
  type: LoadBalancer
  loadBalancerIP: 40.71.36.19
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: miniedgeapp



