apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniedgeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miniedgeapp
  template:
    metadata:
      labels:
        app: miniedgeapp
    spec:
      containers:
      - name: miniedgeapp
        image: miniedgeappacr.azurecr.io/minimal_edge_app1:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REGION
          value: "eastus"
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
